---

- name: Clock Web APP 
  hosts: "{{ vm_target }}"
  gather_facts: false
  remote_user: ansible
  become: yes
  ignore_errors: yes
  tasks:
    - name: Install Apache and PHP
      apt:
        name: 
          - apache2
          - php
        update_cache: true
        state: latest

    - name: Create clock dir
      file:
        path: /var/www/html/clock/
        owner: root
        group: root
        mode:  '0755'
        state: directory

    - name: Download Frontend
      get_url:
        url: https://raw.githubusercontent.com/immfly/tech-test-infra/d5079bc2ac40880bff3ab3bb05f57b9774b6285d/assets/index.html
        dest: /var/www/html/
        validate_certs: false
        owner: root
        group: root
        mode: 0644

    - name: Create Backend Python file
      file:
        path: /var/www/html/clock/clock.py
        owner: root
        group: root
        mode: 0644
        state: touch

    - name: Create Backend PHP file
      file:
        path: /var/www/html/clock/index.php
        owner: root
        group: root
        mode: 0644
        state: touch

    - name: Config Backend Python
      blockinfile:
        path: /var/www/html/clock/clock.py
        state: present
        block: |
          #!/usr/bin/env python3
          import time
          print(time.time())

    - name: Config Backend PHP
      lineinfile:
        path: /var/www/html/clock/index.php
        state: present
        line: '<?php echo exec("python3 clock.py");?>'

    - name: restart Apache
      service:
        name: apache2
        state: restarted
